problem:
  name: "navier_stokes_2D_obstacle_multigpu"
  re: 50

model:
  type: FNN
  params:
    hidden_layers: [64, 64, 64, 64, 64, 64, 64, 64, 64]

model_target:
  _target_: multipinn.neural_network.${model.type}

regularization:
  type: Pointwise # Constant, Gradient, Normal, null
  params:
    ignored_indexes: [0]
    # lambdas:  [1, 1, 1, 1, 1, 1, 1, 1]

regularization_target:
  _target_: multipinn.regularization.${regularization.type}Losses

generator:
  domain_points: 21_000
  bound_points: 3_000
  sampler: "pseudo"

trainer:
  num_epochs: 100_000
  grid_update: null
  random_seed: 42
  calc_loss: "mean" # "mean", "legacy"
  mixed_training: false  # Can be enabled for additional speedup with compatible hardware

visualization:
  grid_plot_points: 20_000
  save_period: 2000
  save_mode: "png"

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.9999

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

paths:
  save_dir: ${hydra:runtime.cwd}/examples/${problem.name}/artifacts/${model.type}_reg_${regularization.type}_loss_${trainer.calc_loss}_re_${problem.re}_multigpu 