problem:
  name: "convection_1D_marching"
  betta: 30
  t_max: 5
  x_max: torch.pi * 2

model:
  type: FNN
  params:
    hidden_layers: [64, 64, 64, 64, 64, 64, 64, 64, 64]
  marching:
    steps: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
    epochs_per_iter: [30000, 60000, 90000, 120000, 150000, 180000, 210000, 240000, 270000, 300000]

model_target:
  _target_: multipinn.neural_network.${model.type}

regularization:
  type: Constant #AdaptiveConditions, Pointwise, Gradient, Normal, AdaptiveConditions, null
  params:
    # lr: 1e-3
    # ignored_indexes: [0]
    lambdas: [1, 1, 1]

regularization_target:
  _target_: multipinn.regularization.${regularization.type}Losses

generator:
  domain_points: 30_000
  bound_points: 3_000
  sampler: "pseudo"

trainer:
  num_epochs: 300_000
  grid_update: 1_000_000
  random_seed: 42
  calc_loss: "mean" # "mean", "legacy"

visualization:
  grid_plot_points: 20_000
  save_period: 5000
  save_mode: "png"

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.9999

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

paths:
  save_dir: ${hydra:runtime.cwd}/examples/${problem.name}/artifacts/marching_${model.type}_${regularization.type}_betta_${problem.betta}_t_max_${problem.t_max}
